# NumPy Basics
This section provides an introduction to NumPy, a fundamental package for numerical computations in Python.

## ● Importing NumPy
To use NumPy in your Python code, you first need to import it. It's common to import NumPy with the alias `np`.

In [1]:
import numpy as np

## ● Creating Arrays
NumPy's main object is the homogeneous multidimensional array. You can create arrays in several ways:

1. **From Python Lists**: Convert a Python list into a NumPy array.

In [ ]:
# Creating a 1D array
array_1d = np.array([1, 2, 3, 4, 5])

# Creating a 2D array
array_2d = np.array([[1, 2, 3], [4, 5, 6]])

2. **Using Built-in Functions**: NumPy provides several functions to create arrays with initial placeholder content.

- `np.zeros`: Creates an array filled with zeros.
- `np.ones`: Creates an array filled with ones.
- `np.arange`: Creates an array with evenly spaced values within a given interval.
- `np.linspace`: Creates an array with a specified number of evenly spaced values over a specified interval.

In [ ]:
# Array of zeros
zeros_array = np.zeros((3, 4))  # 3 rows, 4 columns

# Array of ones
ones_array = np.ones((2, 5))    # 2 rows, 5 columns

# Array with a range of values
range_array = np.arange(0, 10, 2)  # Start at 0, end before 10, step by 2

# Array with linearly spaced values
linspace_array = np.linspace(0, 1, 5)  # 5 values from 0 to 1

## ● Inspecting Arrays
You can inspect various attributes of arrays:

- `ndim`: Number of dimensions
- `shape`: Dimensions of the array
- `size`: Total number of elements
- `dtype`: Data type of the elements

In [ ]:
array = np.array([[1, 2, 3], [4, 5, 6]])

print("Number of dimensions:", array.ndim)
print("Shape of the array:", array.shape)
print("Total number of elements:", array.size)
print("Data type of elements:", array.dtype)

Number of dimensions: 2
Shape of the array: (2, 3)
Total number of elements: 6
Data type of elements: int64


## ● Array Operations
Arithmetic operations on arrays are applied element-wise.

In [ ]:
a = np.array([10, 20, 30, 40])
b = np.array([1, 2, 3, 4])

# Addition
print("Addition:", a + b)

# Subtraction
print("Subtraction:", a - b)

# Multiplication
print("Multiplication:", a * b)

# Division
print("Division:", a / b)

Addition: [11 22 33 44]
Subtraction: [ 9 18 27 36]
Multiplication: [ 10  40  90 160]
Division: [10. 10. 10. 10.]


## ● Universal Functions
NumPy provides universal functions (ufuncs) which are functions that operate element-wise on arrays.

Examples include `np.sin`, `np.cos`, `np.exp`, etc.

In [ ]:
angles = np.array([0, np.pi/2, np.pi])

# Sine of angles
print("Sine:", np.sin(angles))

# Cosine of angles
print("Cosine:", np.cos(angles))

# Exponential
numbers = np.array([1, 2, 3])
print("Exponential:", np.exp(numbers))

Sine: [0.0000000e+00 1.0000000e+00 1.2246468e-16]
Cosine: [ 1.000000e+00  6.123234e-17 -1.000000e+00]
Exponential: [ 2.71828183  7.3890561  20.08553692]


## ● Indexing and Slicing
You can access elements, slices, and subarrays of NumPy arrays using indexing.

In [ ]:
array = np.array([[1, 2, 3], [4, 5, 6]])

# Accessing element at row 0, column 1
print("Element at (0,1):", array[0, 1])

# Slicing rows
print("First row:", array[0, :])

# Slicing columns
print("Second column:", array[:, 1])

## ● Reshaping Arrays
You can change the shape of an array without changing its data using `reshape`.

In [ ]:
array = np.arange(12)  # Creates an array with elements from 0 to 11

# Reshaping to 3 rows and 4 columns
reshaped_array = array.reshape((3, 4))
print("Reshaped Array:\n", reshaped_array)

Reshaped Array:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


## ● Broadcasting
Broadcasting allows NumPy to perform operations on arrays of different shapes.

In [ ]:
a = np.array([1, 2, 3])
b = np.array([[10], [20], [30]])

# Broadcasting addition
result = a + b
print("Broadcasted Addition:\n", result)

Broadcasted Addition:
 [[11 12 13]
 [21 22 23]
 [31 32 33]]


## ● Random Number Generation
NumPy provides functions to generate random numbers.

- `np.random.rand`: Generates uniform random numbers between 0 and 1.
- `np.random.randn`: Generates standard normal distributed numbers.
- `np.random.randint`: Generates random integers within a specified range.

In [ ]:
# Uniform random numbers (from 0 to 1)
uniform_random = np.random.rand(3, 2)  # 3 rows, 2 columns

# Standard normal distributed numbers
normal_random = np.random.randn(4)  # 1D array with 4 elements
print(normal_random)

# Random integers between 0 and 10
random_integers = np.random.randint(0, 10, size=(2,3))  # 2 rows, 3 columns

[ 0.43284002 -2.6471777   0.18164593 -0.65973056]


## ● Summation
You can use `np.sum` to calculate the sum of all elements in an array or along a specific axis.

In [3]:
array = np.array([[1, 2, 3], [4, 5, 6]])

# Sum of all elements
total_sum = np.sum(array)
print("Total sum:", total_sum)

# Sum along rows
row_sum = np.sum(array, axis=1)
print("Sum along rows:", row_sum)

# Sum along columns
column_sum = np.sum(array, axis=0)
print("Sum along columns:", column_sum)

Total sum: 21
Sum along rows: [ 6 15]
Sum along columns: [5 7 9]


## ● Average (Mean)
You can use `np.mean` to calculate the average (mean) of all elements in an array or along a specific axis.

In [ ]:
array = np.array([[1, 2, 3], [4, 5, 6]])

# Mean of all elements
total_mean = np.mean(array)
print("Total mean:", total_mean)

# Mean along rows
row_mean = np.mean(array, axis=1)
print("Mean along rows:", row_mean)

# Mean along columns
column_mean = np.mean(array, axis=0)
print("Mean along columns:", column_mean)

## ● Maximum and Minimum
You can use `np.max` and `np.min` to find the maximum and minimum values in an array or along a specific axis.

In [2]:
array = np.array([[1, 2, 3], [4, 5, 6]])

# Maximum value in the array
max_value = np.max(array)
print("Maximum value:", max_value)

# Minimum value in the array
min_value = np.min(array)
print("Minimum value:", min_value)

# Maximum along rows
row_max = np.max(array, axis=1)
print("Maximum along rows:", row_max)

# Minimum along columns
column_min = np.min(array, axis=0)
print("Minimum along columns:", column_min)

Maximum value: 6
Minimum value: 1
Maximum along rows: [3 6]
Minimum along columns: [1 2 3]
